### ISSUE TITLE
refactor auth flow to standalone npm package

### ISSUE THREAD

**Issue by Burwin** [heroiq/catholic-per-day#6]
# Summary
Getting the auth access token from Twitter via an automated process is annoying. This package should make that easier for everybody.

# Tasks
- [ ] Standalone NPM package
- [ ] Single async method
- [ ] Method uses `refresh_token` - if provided - to get a new `access_token`
- [ ] If not provided, it goes through the full flow to get a brand new `refresh_token` and `access_token`
- [ ] Documentation talks about setting up Twitter and persistence of tokens
